### PR TITLE
Master port to OM - GeneralCatalog

### PR DESCRIPTION
**Pull request by s7design**
Hi @UdoBretz ,

Hereby is first port to OM for ITSM modules with selenium tests. 
There is just one remark, that i would like to point out. Do you want to place Output files in similar structure how we did when porting OTRS  Output modules. 
Like for example: "Kernel/Output/HTML/GeneralCatalogPreferences/Generic.pm". If this is way you would like to do we can update this PR and .xml files accordingly to it.

If there are any question or feedback, please do not hesitate to contact us.

Regards,
Sanjin
S7

### CODE REVIEW

**Comment by mgruner** [comment]
Hi Sanjin,

yes, please use the same structure in Kernel/Output/HTML. Next week I
will make one more (final) change, to move the templates into a
Templates/ subdirectory. You'll have to update the port then, but that
one will be easy. ;)

Best regards, mg

Am 04.06.15 um 17:41 schrieb S7 Design:
> Hi @UdoBretz <https://github.com/UdoBretz> ,
> 
> Hereby is first port to OM for ITSM modules with selenium tests.
> There is just one remark, that i would like to point out. Do you want to
> place Output files in similar structure how we did when porting OTRS
> Output modules.
> Like for example:
> "Kernel/Output/HTML/GeneralCatalogPreferences/Generic.pm". If this is
> way you would like to do we can update this PR and .xml files
> accordingly to it.
> 
> If there are any question or feedback, please do not hesitate to contact us.
> 
> Regards,
> Sanjin
> S7
> 
> ------------------------------------------------------------------------
> 
> 
>         You can view, comment on, or merge this pull request online at:
> 
>   https://github.com/OTRS/GeneralCatalog/pull/3
> 
> 
>         Commit Summary
> 
>   * port to OM
>   * selenium tests
>   * update
> 
> 
>         File Changes
> 
>   * *M* Kernel/Config/Files/GeneralCatalog.xml
>     <https://github.com/OTRS/GeneralCatalog/pull/3/files#diff-0> (2)
>   * *M* Kernel/Modules/AdminGeneralCatalog.pm
>     <https://github.com/OTRS/GeneralCatalog/pull/3/files#diff-1> (135)
>   * *M* Kernel/Output/HTML/GeneralCatalogPreferencesGeneric.pm
>     <https://github.com/OTRS/GeneralCatalog/pull/3/files#diff-2> (21)
>   * *A* scripts/test/Selenium/Agent/Admin/AdminGeneralCatalog.t
>     <https://github.com/OTRS/GeneralCatalog/pull/3/files#diff-3> (199)
>   * *A* scripts/test/Selenium/Output/GenralCatalogPreferencesGeneric.t
>     <https://github.com/OTRS/GeneralCatalog/pull/3/files#diff-4> (157)
> 
> 
>         Patch Links:
> 
>   * https://github.com/OTRS/GeneralCatalog/pull/3.patch
>   * https://github.com/OTRS/GeneralCatalog/pull/3.diff
> 
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/OTRS/GeneralCatalog/pull/3>.
> 

-- 
Martin Gruner
Senior Developer R&D

OTRS AG
Bahnhofplatz 1a
94315 Straubing

T: +49 (0)6172 681988 0
F: +49 (0)9421 56818 18
I:  www.otrs.com/

Geschäftssitz: Bad Homburg, Amtsgericht: Bad Homburg, HRB 10751,
USt-Nr.: DE256610065
Aufsichtsratsvorsitzender: Burchard Steinbild, Vorstand: André
Mindermann (Vorsitzender), Christopher Kuhn, Sabine Riedel

Grenzenlose Kommunikation mit der OTRS Business Solution™! Bereichern
Sie Ihren IT Support und Kundenservice mit smarten Business Features!
https://www.otrs.com/solutions/otrs-business-solution-on-premise/?lang=de/#OTRS-Business-Solution-Basic-Features

**Comment by s7design** [comment]
Hi @mgruner,

It is OK, it will be done soon.
Please let me know when you're done the changes with Templates, you know that we like new tasks :)

Regards
Zoran

**Comment by s7design** [comment]
HI @mgruner ,

PR is updated with new structure for Output file. Also selenium test is improved. I excluded testing GeneralCatalogPreferences###IncidentStates from selenium test for GeneralCatalogPreferenceGeneric.t, that one is connected with ITSMCore. Can write new test once that module is ported, or can include it in this one. Let me know what do you think about it.

Regards,
Sanjin

**Comment by mgruner** [comment]
Please direct all ITSM issues to Udo. Thanks!

Am 05.06.15 um 15:38 schrieb S7 Design:
> HI @mgruner <https://github.com/mgruner> ,
> 
> PR is updated with new structure for Output file. Also selenium test is
> improved. I excluded testing GeneralCatalogPreferences###IncidentStates
> from selenium test for GeneralCatalogPreferenceGeneric.t, that one is
> connected with ITSMCore. Can write new test once that module is ported,
> or can include it in this one. Let me know what do you think about it.
> 
> Regards,
> Sanjin
> 
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/OTRS/GeneralCatalog/pull/3#issuecomment-109294839>.
> 

-- 
Martin Gruner
Senior Developer R&D

OTRS AG
Bahnhofplatz 1a
94315 Straubing

T: +49 (0)6172 681988 0
F: +49 (0)9421 56818 18
I:  www.otrs.com/

Geschäftssitz: Bad Homburg, Amtsgericht: Bad Homburg, HRB 10751,
USt-Nr.: DE256610065
Aufsichtsratsvorsitzender: Burchard Steinbild, Vorstand: André
Mindermann (Vorsitzender), Christopher Kuhn, Sabine Riedel

Grenzenlose Kommunikation mit der OTRS Business Solution™! Bereichern
Sie Ihren IT Support und Kundenservice mit smarten Business Features!
https://www.otrs.com/solutions/otrs-business-solution-on-premise/?lang=de/#OTRS-Business-Solution-Basic-Features

**Comment by mgruner** [comment]
Hi Sanjin, the template location was changed yesterday.

**Comment by s7design** [comment]
Hi @mgruner and @UdoBretz 

I updated PR and changed path for template path. I also updated GeneralCatalog.pm

Regards
Zoran

**Comment by UdoBretz** [comment]
Merged! Thank you!

**Pull request closed without merging**
